# In TypeScript actions, `dist/` is a special directory. When you reference
# an action with the `uses:` property, `dist/index.js` is the code that will be
# run. For this project, the `dist/index.js` file is transpiled from other
# source files. This workflow ensures the `dist/` directory contains the
# expected transpiled code.
#
# If this workflow is run from a feature branch, it will act as an additional CI
# check and fail if the checked-in `dist/` directory does not match what is
# expected from the build.
---
name: Compile

on:
  pull_request_target:

permissions:
  contents: read

jobs:
  check-dist:
    name: Check distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install deps
        run: npm ci
      - name: Bundle
        run: npm run bundle
      - name: Compare distributions
        id: diff
        run: |
          if [ \
            "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" \
          ]; then
            echo "Detected uncommitted changes after build. See status below:";
            git diff --ignore-space-at-eol --text dist/;
            exit 1;
          fi
      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
        name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
