name: Package

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'coverage/**'
      - 'devdist/**'
      - 'dist/**'
      - 'docs/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Install npm deps
        run: npm ci --include=dev
      - name: Package
        run: npm run package
      - if: github.event_name == 'push'
        name: Commit Build Artifacts (coverage, dist, devdist, docs)
        run: |
          git config --global user.name "GitHubActions"
          git config --global user.email "<>"
          git add coverage devdist dist docs
          git commit -m "Updated build artifacts"
          git push
      - if: github.event_name == 'pull_request'
        name: Compress artifact
        run: tar -czvf dist.tar.gz dist
      - if: github.event_name == 'pull_request'
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist.tar.gz
          retention-days: 1

  test:
    name: Integration test
    runs-on: ubuntu-latest
    needs: package
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Decompress artifact
        run: tar -xzvf dist.tar.gz
      - name: Notify
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mapping: >
            - label: help wanted
              message: 'Hey !{{ recipients }}, please help me!'
              recipients:
                - '@iamfj'
            - label: bug
              recipients:
                - '@iamfj'
